backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'data'
    label: 'Navbar & Footer'
    files:
      - file: 'src/data/navbar.md'
        label: 'Navbar'
        name: 'navbar'
        fields:
          - {
              label: 'Data Key',
              name: 'dataKey',
              widget: 'hidden',
              default: 'navbar',
            }
          - { label: 'Logo', name: logo, widget: image }
          - {
              label: 'Menu items',
              name: 'menuitems',
              widget: 'list',
              fields:
                [
                  { label: 'Title', name: 'title' },
                  { label: 'Link', name: 'link' },
                ],
            }
      - file: 'src/data/footer.md'
        label: 'Footer'
        name: 'footer'
        fields:
          - {
              label: 'Data Key',
              name: 'dataKey',
              widget: 'hidden',
              default: 'footer',
            }
          - label: 'Section One'
            name: 'section1'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: 'Social links',
                  name: 'socialLinks',
                  widget: 'object',
                  fields:
                    [
                      { label: 'Facebook', name: 'facebook', widget: string },
                      { label: 'Youtube', name: 'youtube', widget: string },
                      { label: 'Pinterest', name: 'pinterest', widget: string },
                      { label: 'Linkedin', name: 'linkedin', widget: string },
                    ],
                }
          - label: 'Section Two'
            name: 'section2'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: 'Links',
                  name: 'links',
                  widget: 'list',
                  fields:
                    [
                      { label: 'Title', name: 'title' },
                      { label: 'Link', name: 'link' },
                    ],
                }
          - label: 'Section Three'
            name: 'section3'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: 'Links',
                  name: 'links',
                  widget: 'list',
                  fields:
                    [
                      { label: 'Title', name: 'title' },
                      { label: 'Link', name: 'link' },
                    ],
                }
          - label: 'Section Four'
            name: 'section4'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: 'Button Text', name: buttonText, widget: string }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Tagline', name: 'tagline', widget: 'string' }
          - {
              label: 'Feature tags',
              name: 'featureTags',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Item 1',
                    name: 'item1',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Item 2',
                    name: 'item2',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Item 3',
                    name: 'item3',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Item 4',
                    name: 'item4',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                ],
            }
          - {
              label: 'Section 2',
              name: 'section2',
              widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Tagline', name: 'tagline', widget: 'string' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  {
                    label: 'Button Text',
                    name: 'buttonText',
                    widget: 'string',
                  },
                  {
                    label: 'Button Link',
                    name: 'buttonLink',
                    widget: 'string',
                  },
                ],
            }
          - {
              label: 'Section 3',
              name: 'section3',
              widget: 'object',
              fields:
                [
                  { label: 'Tagline', name: 'tagline', widget: 'string' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Content List',
                    name: 'contentList',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Title', name: 'title' },
                        {
                          label: 'Description',
                          name: 'description',
                          widget: 'text',
                        },
                      ],
                  },
                  { label: 'Image', name: 'image', widget: 'image' },
                ],
            }
          - {
              label: 'Section 4',
              name: 'section4',
              widget: 'object',
              fields:
                [
                  { label: 'Tagline', name: 'tagline', widget: 'string' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Category List',
                    name: 'categoryList',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Title', name: 'title' },
                        { label: 'Link', name: 'link' },
                      ],
                  },
                ],
            }
