backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'quote', name: 'quote', widget: 'markdown' }
      - {
          label: 'Pros',
          name: 'pros',
          widget: 'list',
          field: { label: 'Pros', name: 'pros', widget: 'string' },
        }
      - {
          label: 'Cons',
          name: 'cons',
          widget: 'list',
          field: { label: 'Cons', name: 'cons', widget: 'string' },
        }
      - { label: 'Product Image', name: 'productImage', widget: image }
      - { label: 'Product Details', name: 'productDetails', widget: markdown }
      - {
          label: 'Button',
          name: 'button',
          widget: relation,
          collection: 'data',
          value_field: 'buttons.items.link',
          search_fields: ['buttons.items.title'],
          display_fields: ['buttons.items.title'],
        }
      - {
          label: 'Table',
          name: 'table',
          widget: list,
          fields:
            [
              { label: 'Name', name: 'name', widget: string },
              { label: 'Value', name: 'value', widget: string },
            ],
        }
      - {
          label: 'Gauges',
          name: 'gauges',
          widget: object,
          fields:
            [
              {
                label: 'Mode 1',
                name: 'mode1',
                widget: object,
                fields:
                  [
                    {
                      label: 'Value (in percent)',
                      name: 'value',
                      widget: number,
                      min: 0,
                      max: 100,
                    },
                    { label: 'Title', name: 'title', widget: string },
                    {
                      label: 'Features',
                      name: 'features',
                      widget: list,
                      field:
                        { label: 'Feature', name: 'feature', widget: string },
                    },
                  ],
              },
              {
                label: 'Mode 2',
                name: 'mode2',
                widget: object,
                fields:
                  [
                    {
                      label: 'Value (in percent)',
                      name: 'value',
                      widget: number,
                      min: 0,
                      max: 100,
                    },
                    { label: 'Title', name: 'title', widget: string },
                    {
                      label: 'Features',
                      name: 'features',
                      widget: list,
                      field:
                        { label: 'Feature', name: 'feature', widget: string },
                    },
                  ],
              },
              {
                label: 'Mode 3',
                name: 'mode3',
                widget: object,
                fields:
                  [
                    {
                      label: 'Value (in percent)',
                      name: 'value',
                      widget: number,
                      min: 0,
                      max: 100,
                    },
                    { label: 'Title', name: 'title', widget: string },
                    {
                      label: 'Features',
                      name: 'features',
                      widget: list,
                      field:
                        { label: 'Feature', name: 'feature', widget: string },
                    },
                  ],
              },
            ],
        }
      - {
          label: 'Related Articles',
          name: 'relatedArticles',
          widget: object,
          fields:
            [
              {
                label: 'Article 1',
                name: 'article1',
                widget: relation,
                collection: 'blog',
                value_field: 'slug',
                search_fields: ['title'],
                display_fields: ['title'],
              },
              {
                label: 'Article 2',
                name: 'article2',
                widget: relation,
                collection: 'blog',
                value_field: 'slug',
                search_fields: ['title'],
                display_fields: ['title'],
              },
              {
                label: 'Article 3',
                name: 'article3',
                widget: relation,
                collection: 'blog',
                value_field: 'slug',
                search_fields: ['title'],
                display_fields: ['title'],
              },
            ],
        }

  - name: 'data'
    label: 'Data'
    files:
      - file: 'src/data/navbar.md'
        label: 'Navbar'
        name: 'navbar'
        fields:
          - {
              label: 'Data Key',
              name: 'dataKey',
              widget: 'hidden',
              default: 'navbar',
            }
          - { label: 'Logo', name: logo, widget: image }
          - {
              label: 'Menu items',
              name: 'menuitems',
              widget: 'list',
              fields:
                [
                  { label: 'Title', name: 'title' },
                  { label: 'Link', name: 'link' },
                ],
            }
      - file: 'src/data/footer.md'
        label: 'Footer'
        name: 'footer'
        fields:
          - {
              label: 'Data Key',
              name: 'dataKey',
              widget: 'hidden',
              default: 'footer',
            }
          - label: 'Section One'
            name: 'section1'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: 'Social links',
                  name: 'socialLinks',
                  widget: 'object',
                  fields:
                    [
                      { label: 'Facebook', name: 'facebook', widget: string },
                      { label: 'Youtube', name: 'youtube', widget: string },
                      { label: 'Pinterest', name: 'pinterest', widget: string },
                      { label: 'Linkedin', name: 'linkedin', widget: string },
                    ],
                }
          - label: 'Section Two'
            name: 'section2'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: 'Links',
                  name: 'links',
                  widget: 'list',
                  fields:
                    [
                      { label: 'Title', name: 'title' },
                      { label: 'Link', name: 'link' },
                    ],
                }
          - label: 'Section Three'
            name: 'section3'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: 'Links',
                  name: 'links',
                  widget: 'list',
                  fields:
                    [
                      { label: 'Title', name: 'title' },
                      { label: 'Link', name: 'link' },
                    ],
                }
          - label: 'Section Four'
            name: 'section4'
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: 'Button Text', name: buttonText, widget: string }
      - file: 'src/data/buttons.md'
        name: 'buttons'
        label: 'Buttons'
        fields:
          - {
              label: 'Data Key',
              name: 'dataKey',
              widget: 'hidden',
              default: 'buttons',
            }
          - {
              label: 'Buttons',
              name: 'items',
              widget: list,
              fields:
                [
                  { label: 'Title', name: 'title', widget: string },
                  { label: 'Link', name: 'link', widget: string },
                ],
            }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Tagline', name: 'tagline', widget: 'string' }
          - {
              label: 'Feature tags',
              name: 'featureTags',
              widget: 'object',
              fields:
                [
                  {
                    label: 'Item 1',
                    name: 'item1',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Item 2',
                    name: 'item2',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Item 3',
                    name: 'item3',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                  {
                    label: 'Item 4',
                    name: 'item4',
                    widget: 'object',
                    fields:
                      [
                        { label: 'Image', name: 'image', widget: 'image' },
                        { label: 'Link', name: 'link', widget: 'string' },
                      ],
                  },
                ],
            }
          - {
              label: 'Section 2',
              name: 'section2',
              widget: 'object',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Tagline', name: 'tagline', widget: 'string' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Description', name: 'description', widget: 'text' },
                  {
                    label: 'Button Text',
                    name: 'buttonText',
                    widget: 'string',
                  },
                  {
                    label: 'Button Link',
                    name: 'buttonLink',
                    widget: 'string',
                  },
                ],
            }
          - {
              label: 'Section 3',
              name: 'section3',
              widget: 'object',
              fields:
                [
                  { label: 'Tagline', name: 'tagline', widget: 'string' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Content List',
                    name: 'contentList',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Title', name: 'title' },
                        {
                          label: 'Description',
                          name: 'description',
                          widget: 'text',
                        },
                      ],
                  },
                  { label: 'Image', name: 'image', widget: 'image' },
                ],
            }
          - {
              label: 'Section 4',
              name: 'section4',
              widget: 'object',
              fields:
                [
                  { label: 'Tagline', name: 'tagline', widget: 'string' },
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Category List',
                    name: 'categoryList',
                    widget: 'list',
                    fields:
                      [
                        { label: 'Title', name: 'title' },
                        { label: 'Link', name: 'link' },
                      ],
                  },
                ],
            }
